services:
  web:
    build: .
    container_name: web
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/price_monitor
    command: ./start.sh

  scraper:
    build: .
    container_name: scraper
    depends_on:
      - db
      - redis
    environment:
      - API_URL=http://web:8000
      - DATABASE_URL=postgresql://user:password@db:5432/price_monitor
      - CELERY_BROKER_URL=redis://redis:6379/0
    command: celery -A scrapers.tasks worker --loglevel=info --concurrency=16
    # command: ["/bin/sh", "-c", "celery multi start 8 -A scrapers.tasks --loglevel=info --concurrency=2 --detach && tail -f /dev/null"]

  flower:
    build: .
    container_name: flower
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
    ports:
      - "5555:5555"
    command: celery -A scrapers.tasks flower --port=5555

  celery-beat:
    build: .
    container_name: celery-beat
    depends_on:
      - scraper
      - redis
    environment:
      - API_URL=http://web:8000
      - DATABASE_URL=postgresql://user:password@db:5432/price_monitor
      - CELERY_BROKER_URL=redis://redis:6379/0
    command: celery -A scrapers.tasks beat --loglevel=info

  db:
    image: postgres:13
    container_name: db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: price_monitor
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"

volumes:
  pgdata:
