"""migration 2

Revision ID: 3ca7fb4710d6
Revises: b51b68267a2e
Create Date: 2025-04-19 23:31:22.002624

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3ca7fb4710d6"
down_revision: Union[str, None] = "b51b68267a2e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("products", sa.Column("state", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("products", "state")
    # ### end Alembic commands ###
