"""Add updated_at column to product

Revision ID: 6e9d53089298
Revises: 489dada0eee4
Create Date: 2025-03-22 00:55:06.692894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e9d53089298'
down_revision: Union[str, None] = '489dada0eee4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'updated_at')
    # ### end Alembic commands ###
