"""migration

Revision ID: b51b68267a2e
Revises: 9ff843b68851
Create Date: 2025-04-19 23:28:50.787831

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "b51b68267a2e"
down_revision: Union[str, None] = "9ff843b68851"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_search_active", table_name="search_configs")
    op.drop_index("ix_search_term", table_name="search_configs")
    op.drop_table("search_configs")
    op.add_column(
        "products", sa.Column("seller_name", sa.String(length=20), nullable=True)
    )
    op.drop_column("products", "source")
    op.drop_column("products", "state")
    op.drop_column("products", "seller_type")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "products",
        sa.Column(
            "seller_type", sa.VARCHAR(length=20), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "products",
        sa.Column("state", sa.VARCHAR(length=2), autoincrement=False, nullable=True),
    )
    op.add_column(
        "products",
        sa.Column("source", sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    )
    op.drop_column("products", "seller_name")
    op.create_table(
        "search_configs",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "search_term", sa.VARCHAR(length=255), autoincrement=False, nullable=False
        ),
        sa.Column("is_active", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column(
            "source_websites",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("frequency_days", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "preferred_time", postgresql.TIME(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "search_metadata",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id", name="search_configs_pkey"),
    )
    op.create_index("ix_search_term", "search_configs", ["search_term"], unique=False)
    op.create_index("ix_search_active", "search_configs", ["is_active"], unique=False)
    # ### end Alembic commands ###
